### ISSUE TITLE
Unable to create secondary zone via ns1_zone

### ISSUE THREAD

**Issue by mburtless** [ns1/ns1-ansible-modules#11]
### Expected Behavior ###
A play that uses ns1_zone with a dict passed the `secondary` parameter with both the `enabled` and `primary_ip` keys defined, should create a secondary zone in NS1

### Actual Behavior ###
Execution of the play fails with the following error
```
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "HTTP Error 400: Bad Request - b'{\"message\":\"Input validation failed (Value u\\\\\"[{\\'enabled\\': True, \\'primary_ip\\': \\'1.2.
)\"}\\n'"}
```
### Information About the Issue
Issue is caused because no type is defined on the `secondary` parameter, so all input passed to this parameter is automatically converted by Ansible to a string, while the API requires a dict.

Adding `type='dict'` to the parameter definition resolves this issue and allows the parameter to accept dict input and pass it directly to the API.

### Steps To Reproduce ###
```
- name: Create secondary zone
      local_action:
        module: ns1_zone
        apiKey: "{{ key }}"
        name: "{{ zone_name }}"
        state: present
        secondary:
          enabled: True
          primary_ip: "{{ primary_ip }}"
      register: return
```
